name: Fetch RSS
on:
  schedule:
    - cron: "0 */6 * * *" # 每6小时
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install feedparser
      - run: python scripts/fetch_feeds.py
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data.json
            git commit -m "chore: update data.json from RSS"
            git push
          fi
